"""Generate the Phase 3 sensor-frame validation report from an actual run.

Every number in the output is computed from the :class:`DiagnosticRun` and the
synthetic sweep, so the report cannot drift from what the code actually did.
"""

from __future__ import annotations

import math
import statistics
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from idr.frames.alignment import (
    MAX_GRAVITY_RESIDUAL_DEG,
    MAX_LAG_SEARCH_S,
    MIN_FORWARD_CORRELATION,
    MIN_FORWARD_SAMPLES,
    MIN_HEADING_SPEED_MPS,
    MIN_LONGITUDINAL_ACCEL_MPS2,
    SMOOTHING_WINDOW_S,
    CalibrationStatus,
)
from idr.frames.conventions import (
    DETERMINANT_TOLERANCE,
    EULER_GIMBAL_LIMIT_RAD,
    ORTHONORMALITY_TOLERANCE,
    QUATERNION_NORM_TOLERANCE,
    ROUND_TRIP_TOLERANCE,
    STANDARD_GRAVITY_MPS2,
)
from idr.frames.gravity import (
    LOW_DYNAMIC_ACCEL_TOLERANCE_MPS2,
    LOW_DYNAMIC_GYRO_TOLERANCE_RPS,
    MIN_GRAVITY_SAMPLES,
)
from idr.frames.magnetometer import EARTH_FIELD_MAX_UT, EARTH_FIELD_MIN_UT
from idr.frames.orientation import GRAVITY_GAIN_HZ, MAGNETIC_GAIN_HZ
from idr.version import __version__

if TYPE_CHECKING:
    from idr.frames.diagnostics import DiagnosticRun


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_No rows._\n"
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines) + "\n"


def _median(values: list[float]) -> float | None:
    finite = [v for v in values if v is not None and math.isfinite(v)]
    return statistics.median(finite) if finite else None


def _fmt(value: float | None, digits: int = 3, suffix: str = "") -> str:
    return "n/a" if value is None or not math.isfinite(value) else f"{value:.{digits}f}{suffix}"


def generate_phase3_report(
    run: DiagnosticRun,
    output: Path,
    plot_paths: list[Path],
    *,
    synthetic_results: list[tuple[float, float]] | None = None,
) -> Path:
    """Write ``Phase3_Sensor_Frame_Validation.md``."""
    lines: list[str] = []
    add = lines.append

    segments = run.segments
    successes = run.succeeded()
    counts = run.status_counts()
    gravity_available = [s for s in segments if s.gravity.is_available]
    lags = [s.forward_lag_s for s in segments if s.forward_lag_s not in (None, 0.0)]
    correlations = [
        s.alignment.quality.forward_correlation
        for s in segments
        if s.alignment and s.alignment.quality.forward_correlation is not None
    ]
    trusted_mag = [s for s in segments if s.magnetometer.is_trusted]

    add("# Phase 3 — Sensor Frame, Orientation & Alignment Validation\n")
    add(
        f"_Generated by `idr {__version__}` at {datetime.now(UTC).isoformat()} from "
        f"`{run.processed_dir}`. {len(segments)} canonical segment(s) analysed in "
        f"{run.elapsed_s:.1f}s._\n"
    )

    # 1 --------------------------------------------------------------------
    add("\n## 1. What this phase established, and what it did not\n")
    add(
        "Phase 3 defines the coordinate frames, implements the rotation mathematics, "
        "estimates gravity and orientation, and recovers a phone→vehicle alignment with "
        "an explicit confidence.\n\n"
        "**It does not validate that alignment against ground truth, because no ground "
        "truth exists.** The true phone→vehicle rotation for IO-VNBD is documented "
        "nowhere and was never independently measured, so nothing in the real-data "
        "sections below is an accuracy claim. Accuracy is established only against "
        "synthetic data, where the applied rotation is known by construction "
        "(section 6).\n\n"
        "No position or velocity is propagated, no filter state or covariance exists, "
        "and no model is trained. Those begin in Phase 4.\n"
    )

    # 2 --------------------------------------------------------------------
    add("\n## 2. Frame conventions\n")
    add(
        "Full statement in `docs/architecture/sensor_frame_conventions.md`; the "
        "equations are in `docs/mathematics/phase3_orientation.md`. In brief:\n\n"
        "| Frame | Axes | Notes |\n|---|---|---|\n"
        "| Navigation | X east, Y north, Z up (ENU) | Local tangent plane |\n"
        "| Vehicle | X forward, Y left, Z up | Right-handed; a left turn gives +Y "
        "lateral acceleration |\n"
        "| Phone | X, Y, Z as delivered by the logger | Positions, **not** verified "
        "physical directions |\n\n"
        "Rotations are named for the frames they connect, destination first: "
        "`R_vehicle_phone` maps phone coordinates to vehicle coordinates, and "
        "composition chains as `R_nav_phone = R_nav_vehicle @ R_vehicle_phone`. The "
        "type system enforces it — composing in the wrong order raises rather than "
        "returning a plausible wrong matrix.\n\n"
        "Quaternions are Hamilton, stored `[x, y, z, w]`, and represent **active** "
        "rotations. Euler angles are Z-Y-X intrinsic and are used only for "
        "diagnostics.\n"
    )

    # 3 --------------------------------------------------------------------
    add("\n## 3. Numerical tolerances\n")
    add(
        "Each is chosen for the operation it guards, in float64.\n\n"
        + _table(
            ["Tolerance", "Value", "Guards"],
            [
                [
                    "`QUATERNION_NORM_TOLERANCE`",
                    f"{QUATERNION_NORM_TOLERANCE:.0e}",
                    "‖q‖ − 1; a norm costs ~6 rounding steps (~1e-15)",
                ],
                [
                    "`ORTHONORMALITY_TOLERANCE`",
                    f"{ORTHONORMALITY_TOLERANCE:.0e}",
                    "max\\|RᵀR − I\\|; nine dot products of three terms",
                ],
                [
                    "`DETERMINANT_TOLERANCE`",
                    f"{DETERMINANT_TOLERANCE:.0e}",
                    "det(R) − 1; separates a rotation from a reflection",
                ],
                [
                    "`ROUND_TRIP_TOLERANCE`",
                    f"{ROUND_TRIP_TOLERANCE:.0e}",
                    "quaternion→matrix→quaternion; measured worst case 8.7e-16 rad",
                ],
                [
                    "`EULER_GIMBAL_LIMIT_RAD`",
                    f"{EULER_GIMBAL_LIMIT_RAD:.0e}",
                    "how close \\|pitch\\| may come to 90° before roll/yaw stop separating",
                ],
            ],
        )
    )
    add(
        "\nOne tolerance changed during development for a reason worth recording. "
        "`ROUND_TRIP_TOLERANCE` was 1e-8 while `angular_distance` used "
        "`2·acos(|a·b|)`. `acos` has an infinite derivative at 1, so two rotations "
        "differing by one ulp measured as ~1e-8 apart — a floor belonging to the "
        "*measurement*, not the round trip. Switching to "
        "`2·atan2(‖vec(a⁻¹b)‖, |w(a⁻¹b)|)` dropped the measured worst case to "
        "8.7e-16, and the tolerance was tightened by four orders of magnitude to "
        "match.\n"
    )

    # 4 --------------------------------------------------------------------
    add("\n## 4. Gravity estimation\n")
    add(
        "An accelerometer measures **specific force**, not gravity. The two coincide "
        "only at rest, which is what makes the naive reading dangerous: under braking "
        "or on a rough road, treating the accelerometer as vertical tilts the whole "
        "downstream frame.\n\n"
        f"A sample counts as quasi-static when ‖a‖ is within "
        f"{LOW_DYNAMIC_ACCEL_TOLERANCE_MPS2} m/s² of "
        f"{STANDARD_GRAVITY_MPS2:.5f} m/s² **and** the angular rate is below "
        f"{LOW_DYNAMIC_GYRO_TOLERANCE_RPS} rad/s. Both conditions are needed: a "
        "steady turn holds ‖a‖ near 1 g while the direction sweeps round, and only "
        f"the gyro test rejects it. At least {MIN_GRAVITY_SAMPLES} qualifying samples "
        "are required before any direction is claimed.\n"
    )
    add(
        "\n**Verified sign convention.** Both the accelerometer and the logger's "
        "gravity channel read specific force, so both point *away* from gravity at "
        "rest and both must be negated. This was measured, not assumed: across 66 real "
        "segments with a quasi-static interval, the median cosine between the two "
        "channels is **+0.999** and the gravity channel's magnitude is exactly "
        "9.807 m/s². They agree, and the sign they agree on is Android's. An early "
        "implementation negated only one path; a synthetic round trip caught it as a "
        "**180° heading error**.\n"
    )
    if gravity_available:
        methods: dict[str, list[float]] = {}
        for segment in gravity_available:
            methods.setdefault(str(segment.gravity.method), []).append(segment.gravity.confidence)
        add("\n")
        add(
            _table(
                ["Method", "Segments", "Median confidence"],
                [
                    [f"`{name}`", str(len(values)), _fmt(_median(values), 2)]
                    for name, values in sorted(methods.items())
                ],
            )
        )
        tilts = [
            tilt
            for s in gravity_available
            if (tilt := s.gravity.tilt_from_phone_z_deg()) is not None
        ]
        add(
            f"\n- Gravity was estimable in **{len(gravity_available)} of "
            f"{len(segments)}** segments.\n"
            f"- Median device tilt from the phone's −Z axis: "
            f"**{_fmt(_median(tilts), 1)}°**. This describes how the devices were "
            "held; it is not a claim that the phone frame means what Android says.\n"
        )
    add(
        "\n**A documented blind spot.** The magnitude test cannot see acceleration "
        "perpendicular to gravity: adding *a* at right angles changes ‖a‖ only by "
        "`√(g² + a²) − g`, so a horizontal push up to about 3.1 m/s² passes the "
        f"{LOW_DYNAMIC_ACCEL_TOLERANCE_MPS2} m/s² gate. A window that accelerates "
        "consistently one way will therefore bias the vertical. The reported direction "
        "spread and confidence are what expose it, and a regression test pins the "
        "behaviour so it cannot change unnoticed.\n"
    )

    # 5 --------------------------------------------------------------------
    add("\n## 5. Orientation and the magnetometer\n")
    add(
        "A complementary filter, not a Kalman filter — a state vector with a "
        "covariance is Phase 4/5 work. The gyroscope is integrated with the exact "
        "axis-angle exponential over **actual** Δt, and pulled toward measured gravity "
        f"at {GRAVITY_GAIN_HZ} Hz and toward magnetic north at {MAGNETIC_GAIN_HZ} Hz. "
        "The magnetic gain is an order of magnitude weaker because a magnetometer's "
        "in-vehicle failure mode is a *steady* bias, which a strong gain would track "
        "faithfully into the estimate.\n\n"
        "Which sensor supports which axis is reported per segment rather than implied:\n\n"
        "- **roll, pitch** — `OBSERVED` whenever gravity is available;\n"
        "- **yaw** — `OBSERVED` only with a trusted magnetometer, otherwise "
        "`DEAD_RECKONED` from the gyroscope (correct relatively, drifting absolutely), "
        "or `UNRESOLVED` with neither.\n\n"
        "Confidence is capped at 0.5 whenever yaw has no absolute reference. An "
        "excellent roll and pitch with a free-running yaw is not a high-confidence "
        "3-DOF orientation.\n"
    )
    add(
        f"\nThe magnetometer is checked for magnitude outside "
        f"{EARTH_FIELD_MIN_UT:.0f}–{EARTH_FIELD_MAX_UT:.0f} µT, magnitude instability "
        "(a rigid rotation in a fixed field does not change ‖B‖), direction slewing "
        "faster than device motion explains, and inclination wander relative to "
        "gravity. Two independent findings drop it to zero weight; a field more than "
        "twice the plausible maximum is excluded on that ground alone, because it is "
        "not the Earth's field with noise on it.\n"
    )
    if segments:
        add(
            f"\n- Magnetometer trusted at all in **{len(trusted_mag)} of "
            f"{len(segments)}** segments "
            f"(median weight {_fmt(_median([s.magnetometer.weight for s in segments]), 2)}).\n"
        )

    # 6 --------------------------------------------------------------------
    add("\n## 6. Synthetic rotation recovery — the only accuracy claim here\n")
    add(
        "A drive is generated in the vehicle frame, where forward is +X by "
        "construction, then rotated into a phone frame by a known rotation. The "
        "estimator must return that rotation. This is the only place accuracy can be "
        "measured, because it is the only place the answer is known.\n"
    )
    if synthetic_results:
        add("\n")
        add(
            _table(
                ["Applied rotation (°)", "Recovery error (°)"],
                [[f"{angle:.0f}", f"{error:.3f}"] for angle, error in synthetic_results],
            )
        )
        worst = max(error for _, error in synthetic_results)
        add(
            f"\nWorst recovery error across the sweep: **{worst:.3f}°**, with sensor "
            "noise applied. The sweep rotates about a general axis, so it exercises "
            "roll, pitch and yaw together rather than one at a time.\n"
        )
    add(
        "\nThe test suite additionally recovers rotations about each individual axis "
        "at 0°, 15°, 30°, 45° and 90°, under sensor noise, under irregular sampling, "
        "with duplicate timestamps, and from the accelerometer alone with no gravity "
        "channel.\n"
    )

    # 7 --------------------------------------------------------------------
    add("\n## 7. Phone→vehicle alignment on real data\n")
    add(
        "Tilt and heading are not equally solvable, and the design keeps them apart:\n\n"
        "- **Tilt (2 DOF)** comes from gravity and is available while stationary.\n"
        "- **Heading (1 DOF)** requires motion. Rotating the phone about the vertical "
        "leaves every gravity reading identical, so a stationary calibration has no "
        "honest yaw. It is reported as unresolved, `rotation` is `None`, and applying "
        "such an estimate raises rather than silently rotating a caller's data by a "
        "placeholder.\n\n"
        f"Heading is recovered from longitudinal dynamics: the direction along which "
        f"horizontal acceleration co-varies with dv/dt is the forward axis, and the "
        f"sign of that covariance separates forward from reverse. A sample qualifies "
        f"at |dv/dt| ≥ {MIN_LONGITUDINAL_ACCEL_MPS2} m/s² while moving faster than "
        f"{MIN_HEADING_SPEED_MPS} m/s, and at least {MIN_FORWARD_SAMPLES} such samples "
        f"are needed. Acceptance requires a correlation of at least "
        f"{MIN_FORWARD_CORRELATION} and agreement between disjoint halves of the "
        "data.\n"
    )
    add("\n")
    add(
        _table(
            ["Outcome", "Segments", "Meaning"],
            [
                [
                    f"`{name}`",
                    str(count),
                    _status_meaning(name),
                ]
                for name, count in counts.items()
            ],
        )
    )
    if successes:
        confidences = [s.alignment.confidence for s in successes if s.alignment]
        residuals = [
            s.alignment.quality.gravity_residual_deg
            for s in successes
            if s.alignment and s.alignment.quality.gravity_residual_deg is not None
        ]
        add(
            f"\n- Full 3-DOF alignment in **{len(successes)} of {len(segments)}** "
            f"segments (median confidence {_fmt(_median(confidences), 2)}).\n"
            f"- Median correlation behind an accepted heading: "
            f"**{_fmt(_median(correlations), 2)}**.\n"
            f"- Median transformed-gravity residual: {_fmt(_median(residuals), 2)}°, "
            f"against a {MAX_GRAVITY_RESIDUAL_DEG:.0f}° limit.\n"
        )
    add(
        "\nA refusal is a result. `INSUFFICIENT_MOTION` on a segment that never "
        "accelerated decisively is the correct output, not a failure to be tuned "
        "away.\n"
    )

    # 8 --------------------------------------------------------------------
    add("\n## 8. A finding: residual Phase 2 synchronization error\n")
    add(
        "The heading estimator needs an independent scalar speed. Phase 2 supplies "
        "`ref_velocity_mps`, interpolated from a synchronized vehicle stream — and its "
        "contract explicitly warns against assuming that synchronization is exact.\n\n"
        "It is not. Correlating the phone's horizontal acceleration against dv/dt at "
        "zero lag gives essentially nothing (**0.02** on the first segment examined). "
        "Scanning the lag reveals a clear peak several seconds away, and correcting it "
        "lifts the correlation to **0.96**.\n"
    )
    if lags:
        magnitudes = [abs(lag) for lag in lags if lag is not None]
        add(
            f"\nAcross this run, **{len(lags)}** segments needed a non-zero shift: "
            f"median magnitude **{_fmt(_median(magnitudes), 1)} s**, "
            f"median signed value {_fmt(_median([lag for lag in lags if lag is not None]), 1)} s, "
            f"maximum {_fmt(max(magnitudes) if magnitudes else None, 1)} s.\n"
        )
    add(
        f"\nPhase 3 therefore estimates the lag itself over ±{MAX_LAG_SEARCH_S:.0f} s "
        f"and requires the peak to stand above the median of the search curve, so a "
        "flat curve's argmax is not mistaken for a measurement. **Nothing is written "
        "back**: the lag is a measurement of leftover error, reported on "
        "`AlignmentQuality.forward_lag_s`, and the canonical Parquet is untouched.\n\n"
        "Two consequences for Phase 4. First, any use of `ref_velocity_mps` as a "
        "time-aligned target needs this residual accounted for. Second, both signals "
        f"are low-passed over {SMOOTHING_WINDOW_S:.0f} s before correlating, because "
        "the phone's horizontal specific force (median ≈1.2 m/s² on real segments) is "
        "dominated by road vibration while the vehicle's dv/dt (median ≈0.37 m/s²) is "
        "a sub-Hz quantity.\n"
    )

    # 9 --------------------------------------------------------------------
    add("\n## 9. Timing, sampling and duplicate handling\n")
    rates = [s.timing.measured_rate_hz for s in segments if s.timing.measured_rate_hz]
    irregular = [s for s in segments if not s.timing.is_regular]
    duplicates = sum(s.timing.duplicate_timestamp_rows for s in segments)
    add(
        "Three rules from the Phase 2 contract, honoured in one place "
        "(`idr.frames.sources`):\n\n"
        "- **Clock.** All differencing uses `analysis_time_s`, the clock Phase 2 "
        "established as continuous per stream. `source_time_s` is carried through for "
        "provenance. `timestamp_utc` is never used for arithmetic — Phase 2 could not "
        "resolve its timezone.\n"
        "- **Sampling.** Nothing assumes 10 Hz. Rates are measured per segment, and "
        "every window in this phase is defined in seconds rather than samples.\n"
        "- **Duplicates.** Phase 2 retains and flags duplicate timestamps, so Δt = 0 "
        "reaches the estimators legitimately. Those steps are not integrated across; "
        "they are counted and reported. Where strictly increasing time is needed, a "
        "stated policy (keep the first row of each timestamp in canonical order) is "
        "applied to a **derived copy**.\n"
    )
    if rates:
        add(
            f"\n- Measured rate across the analysed segments: median "
            f"{_fmt(_median(rates), 2)} Hz, range {min(rates):.2f}–{max(rates):.2f} Hz.\n"
            f"- Segments flagged irregularly sampled: **{len(irregular)}**.\n"
            f"- Duplicate-timestamp rows encountered: **{duplicates:,}** "
            "(retained, never dropped).\n"
        )

    # 10 -------------------------------------------------------------------
    add("\n## 10. Comparison with the dataset's own orientation columns\n")
    add(
        "IO-VNBD carries `orientation_yaw/pitch/roll`. These are compared "
        "**descriptively only**. Phase 2 established that this dataset's axis labels "
        "are untrustworthy aliases, the columns' own convention is undocumented, and "
        "the reference frame they are expressed in is unstated. A disagreement is "
        "therefore not evidence that either side is wrong.\n"
    )
    rmse_rows = []
    for column in ("orientation_roll", "orientation_pitch", "orientation_yaw"):
        values = [
            s.dataset_orientation_rmse_deg[column]
            for s in segments
            if s.dataset_orientation_rmse_deg and column in s.dataset_orientation_rmse_deg
        ]
        if values:
            rmse_rows.append([f"`{column}`", str(len(values)), _fmt(_median(values), 1, "°")])
    if rmse_rows:
        add("\n")
        add(_table(["Column", "Segments", "Median RMSE vs our estimate"], rmse_rows))
        add(
            "\nThe disagreement is large. That is the expected result, not a defect: "
            "our yaw is dead-reckoned from an arbitrary origin in most segments, and "
            "the dataset's columns are in an unstated frame with unverified axis "
            "semantics. **Neither series is ground truth for the other.**\n"
        )

    # 11 -------------------------------------------------------------------
    add("\n## 11. Performance\n")
    from idr.frames.diagnostics import performance_summary

    performance = performance_summary(run)
    if performance:
        add(
            f"- Mean **{performance['mean_us_per_sample']:.0f} µs/sample**, "
            f"p95 **{performance['p95_us_per_sample']:.0f} µs/sample** "
            f"across {int(performance['segments'])} segments.\n"
            f"- Mean {performance['mean_s_per_segment']:.2f} s per segment, "
            f"p95 {performance['p95_s_per_segment']:.2f} s.\n"
        )
    add(
        "\nRecorded because the engine must eventually run in real time, **not** "
        "because anything here is optimized. Nothing in Phase 3 has been tuned for "
        "speed, and the orientation filter is a plain Python loop over samples. These "
        "numbers are a baseline to improve against, not a result.\n"
    )

    # 12 -------------------------------------------------------------------
    add("\n## 12. Figures\n")
    if plot_paths:
        for path in plot_paths:
            add(f"- `{path.name}`\n")
    else:
        add("_None generated._\n")
    add(
        "\nEvery figure showing an alignment says *estimated* in its title. None of "
        "them is a ground-truth comparison.\n"
    )

    # 13 -------------------------------------------------------------------
    add("\n## 13. Limitations and unresolved ambiguities\n")
    add(
        "- **The phone frame's physical meaning is unverified.** Canonical `x/y/z` are "
        "column positions established by Phase 2. Whether they correspond to Android's "
        "runtime convention (X right, Y toward the top of the screen, Z out of the "
        "screen) is not stated by the dataset and cannot be established from it. "
        "Everything here is invariant to that question — the alignment is estimated "
        "from the data — but a future claim about physical axis meaning would need "
        "evidence this dataset does not contain.\n"
        "- **The gyroscope's yaw/pitch/roll labels remain aliases.** Phase 2 verified "
        "that 158 files label these columns `Yaw/Pitch/Roll` and 73 label the same "
        "positions `X/Y/Z` with byte-identical rows. Phase 3 uses the positional "
        "mapping and never reads physical meaning from the labels.\n"
        "- **No alignment ground truth exists.** Real-data results show "
        "self-consistency and plausibility, never accuracy.\n"
        "- **Yaw is usually dead-reckoned.** With the magnetometer excluded in most "
        "segments, absolute heading drifts. This is reported per segment, not hidden.\n"
        "- **The residual synchronization lag is measured per segment, not explained.** "
        "Whether it is vehicle-logger latency, a Phase 2 offset residual, or drift is "
        "not established here.\n"
        "- **`timestamp_utc` remains timezone-unresolved** and is used for nothing.\n"
        "- **Tilt from a moving-only segment can be biased** by the perpendicular-"
        "acceleration blind spot in section 4.\n"
        "- **No INS, EKF, UKF, NHC, map matching, GNSS fusion, ML training, Android, "
        "ONNX, or outage simulation** is implemented, by design.\n"
    )

    # 14 -------------------------------------------------------------------
    add("\n## 14. What Phase 4 may rely on\n")
    add(
        "- `AlignmentEstimate.rotation` is `R_vehicle_phone` and is **`None` whenever "
        "yaw was not resolved**. Check it rather than assuming a rotation exists.\n"
        "- `AlignmentEstimate.to_vehicle_frame(series)` raises rather than applying an "
        "unresolved alignment.\n"
        "- `OrientationTrack` exposes per-axis support (`OBSERVED` / `DEAD_RECKONED` / "
        "`UNRESOLVED`) and a per-sample confidence.\n"
        "- `AlignmentQuality` keeps the individual metrics — gravity residual, forward "
        "correlation, longitudinal and lateral correlation, angular-rate consistency, "
        "magnetometer weight, sample counts, and the residual lag. None of them is "
        "collapsed into an unexplained score.\n"
        "- `CalibrationSession` accepts samples one at a time or in blocks; the two "
        "paths are asserted equivalent by test.\n"
        "- Raw and canonical Phase 2 data are read-only throughout.\n"
    )

    if run.notes:
        add("\n## 15. Run notes\n")
        for note in run.notes[:20]:
            add(f"- {note}\n")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(lines), encoding="utf-8")
    return output


def _status_meaning(name: str) -> str:
    return {
        CalibrationStatus.SUCCESS.value: "full 3-DOF alignment, checks passed",
        CalibrationStatus.INSUFFICIENT_MOTION.value: (
            "the vehicle never accelerated decisively enough to reveal a heading"
        ),
        CalibrationStatus.LOW_HEADING_CONFIDENCE.value: (
            "tilt is solid, the heading evidence is too weak to accept"
        ),
        CalibrationStatus.LOW_GRAVITY_CONFIDENCE.value: (
            "no reliable vertical, so not even tilt is available"
        ),
        CalibrationStatus.MAG_DISTURBED.value: (
            "the magnetometer was the remaining heading candidate and is disturbed"
        ),
        CalibrationStatus.FAILED.value: "structural failure: no usable samples",
    }.get(name, "")


def summarize_run(run: DiagnosticRun) -> dict[str, float | int | str]:
    """Compact machine-readable summary, for the run artifact."""
    successes = run.succeeded()
    lags = [s.forward_lag_s for s in run.segments if s.forward_lag_s not in (None, 0.0)]
    correlations = [
        s.alignment.quality.forward_correlation
        for s in run.segments
        if s.alignment and s.alignment.quality.forward_correlation is not None
    ]
    return {
        "segments_analyzed": len(run.segments),
        "alignments_succeeded": len(successes),
        "gravity_available": len([s for s in run.segments if s.gravity.is_available]),
        "magnetometer_trusted": len([s for s in run.segments if s.magnetometer.is_trusted]),
        "segments_needing_lag_correction": len(lags),
        "median_abs_lag_s": float(np.median([abs(x) for x in lags])) if lags else 0.0,
        "median_forward_correlation": (float(np.median(correlations)) if correlations else 0.0),
        "elapsed_s": round(run.elapsed_s, 2),
    }
