"""Generate the Phase 2 preprocessing report from an actual pipeline run.

Every figure in the output is computed from the :class:`PipelineResult`, so the
report cannot drift from what the run actually produced.
"""

from __future__ import annotations

import statistics
from collections import Counter
from pathlib import Path
from typing import TYPE_CHECKING

import numpy as np

from idr.pipeline.canonical import CANONICAL_SCHEMA_VERSION, QualityFlag, schema_for
from idr.pipeline.freshness import STALE_MIN_SECONDS, STALE_UPDATE_MULTIPLE
from idr.pipeline.reference import MAX_INTERPOLATION_GAP_S, TIER_QUALITY
from idr.pipeline.sequences import WindowConfig
from idr.pipeline.splits import DEFAULT_RATIOS
from idr.pipeline.sync import MIN_CORRELATION, MIN_OVERLAP_S, SyncStatus
from idr.pipeline.timeline import (
    CLOCK_RESET_MIN_DROP_S,
    SEGMENT_GAP_MIN_SECONDS,
    SEGMENT_GAP_MULTIPLE,
)
from idr.version import __version__

if TYPE_CHECKING:
    from idr.pipeline.runner import PipelineResult


def _table(headers: list[str], rows: list[list[str]]) -> str:
    if not rows:
        return "_No rows._\n"
    lines = ["| " + " | ".join(headers) + " |", "|" + "|".join(["---"] * len(headers)) + "|"]
    lines.extend("| " + " | ".join(row) + " |" for row in rows)
    return "\n".join(lines) + "\n"


def _fmt(value: float | None, digits: int = 3, suffix: str = "") -> str:
    return "n/a" if value is None or not np.isfinite(value) else f"{value:.{digits}f}{suffix}"


def _median_correlation(pairs: list) -> float | None:
    """Median correlation across pairs that have one."""
    values = [p.correlation for p in pairs if p.correlation is not None]
    return statistics.median(values) if values else None


def generate_phase2_report(result: PipelineResult, output: Path, plot_paths: list[Path]) -> Path:
    """Write ``IO_VNBD_Phase2_Preprocessing_Report.md``."""
    lines: list[str] = []
    add = lines.append

    phone_reads = [r for r in result.reads if r.stream == "smartphone"]
    vehicle_reads = [r for r in result.reads if r.stream == "vehicle"]
    phone_segments = [s for s in result.segments if s.stream == "smartphone"]
    vehicle_segments = [s for s in result.segments if s.stream == "vehicle"]

    multi_segment = [t for t in result.timing if t.segment_count > 1]
    counter_resets = [t for t in result.timing if t.source_counter_reset_count]
    reordered = [t for t in result.timing if t.reordered]
    repaired = [r for r in result.reads if r.repair.applied]
    encoding_warned = [r for r in result.reads if r.encoding_warning]

    sync_status = Counter(str(s.status) for s in result.sync)
    label_sources = Counter(label.label_source for label in result.labels)

    total_rows = sum(result.row_counts.values())
    failed = [e for e in result.errors if e.status == "failed"]

    add("# IO-VNBD Phase 2 — Preprocessing Report\n")
    add(
        f"_Generated by `idr {__version__}`, canonical schema "
        f"`{CANONICAL_SCHEMA_VERSION}`, run `{result.run_id}` at {result.started_at} "
        f"from `{result.raw_path}`._\n"
    )

    # 1 -------------------------------------------------------------------
    add("## 1. Executive summary\n")
    add(
        f"- **{len(result.reads)} source files canonicalized** "
        f"({len(phone_reads)} smartphone, {len(vehicle_reads)} vehicle) into "
        f"**{total_rows:,} canonical rows**, written as Parquet.\n"
        f"- **{len(result.segments)} logical segments** "
        f"({len(phone_segments)} smartphone, {len(vehicle_segments)} vehicle); "
        f"**{len(multi_segment)} file(s) held more than one trip**.\n"
        f"- **{len(result.sync)} S/V pairs synchronized** individually: "
        f"{dict(sorted(sync_status.items()))}.\n"
        f"- Reference labels by tier: {dict(sorted(label_sources.items()))}.\n"
        f"- **{len(result.leakage_violations)} split leakage violation(s)**.\n"
        f"- **{len(failed)} file(s) failed**, {len(result.errors)} error record(s) total.\n"
        f"- Wall time {result.elapsed_s:.1f}s.\n"
    )
    add(
        "> Phase 2 changed no raw file, trained no model, generated no synthetic GNSS "
        "outage, and introduced no 10 Hz resampling. Actual sample timing is preserved.\n"
    )

    # 2 -------------------------------------------------------------------
    add("\n## 2. Inputs\n")
    add(
        f"Raw dataset: `{result.raw_path}` — the immutable tree acquired and SHA-256 "
        "verified in Phase 1. Phase 1's metadata (`schema_inventory.json`, "
        "`sampling_report.csv`, `synchronization_report.csv`, ...) supplied the schema "
        "roles and the findings this phase had to respect.\n"
    )

    # 3 -------------------------------------------------------------------
    add("\n## 3. Raw-data integrity\n")
    add(
        "The pipeline opens raw files read-only and writes exclusively to "
        "`data/processed/`, `data/metadata/` and `reports/`. A regression test "
        "(`test_pipeline_does_not_modify_raw_data`) hashes every input before and after a "
        "full run and asserts equality. Raw integrity is re-verified against the Phase 1 "
        "acquisition manifest in the final validation step.\n"
    )

    # 4 -------------------------------------------------------------------
    add("\n## 4. Canonical schema\n")
    add(
        f"Schema version `{CANONICAL_SCHEMA_VERSION}`. Full field list, dtypes and units in "
        "`data/metadata/io_vnbd/canonical_schema.json`; the contract document is "
        "`docs/datasets/io_vnbd_phase2_contract.md`.\n\n"
        f"- Smartphone record: {len(schema_for('smartphone'))} fields.\n"
        f"- Vehicle record: {len(schema_for('vehicle'))} fields.\n"
        "- Missing numeric values are `NaN`, never `0`. Structurally absent channels are "
        "additionally marked in the per-file feature-availability flags, so a reduced "
        "18-column file's missing magnetometer can never be read as a true zero.\n"
        "- Units are normalized (km/h→m/s, g→m/s², km→m) and both the canonical and the "
        "source unit are recorded per field.\n"
    )
    add(
        "\n**Gyroscope axis naming (important).** 158 files label the three gyroscope "
        "columns `Yaw/Pitch/Roll`; 73 label the *same column positions* `X/Y/Z`. Two files "
        "carrying the same recording under the two headers were verified to have "
        "byte-identical data rows, so these are the same channels under different names. "
        "Canonical fields are `gyro_x/y/z` (device frame) mapped **by position**; the "
        "yaw/pitch/roll labels are recorded as aliases and are **not** trusted as axis "
        "semantics. Phase 3 must establish the device→vehicle rotation itself.\n"
    )

    # 5 -------------------------------------------------------------------
    add("\n## 5. Encoding handling\n")
    encodings = Counter(r.source_encoding for r in result.reads)
    add(
        _table(
            ["Encoding", "Files"],
            [[f"`{name}`", str(count)] for name, count in sorted(encodings.items())],
        )
    )
    add(
        f"\n{len(encoding_warned)} file(s) carried an encoding warning. Smartphone headers mix "
        "raw cp1252 bytes (`m/s²`) with double-encoded UTF-8 (`Â°`) in the same line, so a "
        "strict UTF-8 read fails. The reader tries UTF-8, falls back to cp1252, and records "
        "the encoding and decode method per file; canonical output is UTF-8. Rows from a "
        "warned file carry `ENCODING_WARNING`. No byte is silently replaced.\n"
    )

    # 6 -------------------------------------------------------------------
    add("\n## 6. Schema normalization\n")
    add(
        f"- **{len(repaired)} file(s) repaired** for the one-column shift defect.\n"
        "- Reduced 18-column smartphone files keep their missing magnetometer/orientation "
        "channels as NaN with availability flags set to false.\n"
        "- Unmapped source columns are recorded per file in "
        "`canonical_field_mapping.json` rather than dropped silently.\n"
    )
    if repaired:
        add("\nRepairs applied:\n\n")
        add(
            _table(
                ["File", "Rule", "Confidence"],
                [
                    [f"`{Path(r.source_file).name}`", r.repair.rule, r.repair.confidence]
                    for r in repaired
                ],
            )
        )
        add(
            "\nThe repair is **detected, not assumed**: it requires the parsed frame to have "
            "exactly one surplus column, that column at index 6 to be empty in every row, and "
            "the trailing surplus column to contain data. A healthy file cannot match. The "
            "raw file is untouched; only the derived canonical frame is corrected, and every "
            "affected row carries `SCHEMA_REPAIR`.\n"
        )

    # 7 -------------------------------------------------------------------
    add("\n## 7. Timestamp handling\n")
    axis_counts = Counter(
        str(r.frame["analysis_time_source"].iloc[0]) for r in result.reads if not r.frame.empty
    )
    add(
        "Two source clocks exist and are **not** interchangeable: smartphone files carry an "
        "elapsed-millisecond counter plus a wall-clock `DATE` string "
        "(`YYYY-MM-DD HH:MM:SS:mmm`, milliseconds after a colon); vehicle files carry "
        "seconds-since-midnight with no date.\n\n"
        "Canonical records keep `source_time_s` exactly as written and add "
        "`analysis_time_s`, the continuous clock used for segmentation and alignment:\n\n"
    )
    add(
        _table(
            ["analysis_time_source", "Files"],
            [[f"`{name}`", str(count)] for name, count in sorted(axis_counts.items())],
        )
    )
    add(
        f"\n**Why the wall clock wins for smartphone streams.** {len(counter_resets)} file(s) "
        "restart the elapsed counter mid-recording (e.g. `S-S2.csv` drops from t=186.3 s to "
        "t=0.010 s at row 1863) while their `DATE` column runs straight through. Segmenting "
        "on the counter would fragment one continuous drive, and *sorting* by it would "
        "interleave two trips into a trajectory that never happened. The counter resets are "
        "reported as `source_counter_reset_count` but are not treated as trip boundaries.\n\n"
        f"- Duplicate timestamps: "
        f"{sum(t.duplicate_timestamp_rows for t in result.timing):,} row(s) across "
        f"{len([t for t in result.timing if t.duplicate_timestamp_rows])} file(s). "
        "**All retained**, flagged `DUPLICATE_TIMESTAMP`. No row was dropped.\n"
        f"- Non-monotonic rows: {sum(t.non_monotonic_rows for t in result.timing):,} across "
        f"{len(reordered)} file(s), flagged `NON_MONOTONIC_TIMESTAMP`. Where they occur, rows "
        "are stably sorted **within a segment only** — never across a boundary, so distinct "
        "trips can never be merged.\n"
        "- **No resampling and no 10 Hz assumption.** Every sample keeps its own timestamp.\n"
    )

    # 8 -------------------------------------------------------------------
    add("\n## 8. Trip segmentation\n")
    add(
        "A new segment starts at (a) a backward jump on the analysis clock of at least "
        f"{CLOCK_RESET_MIN_DROP_S} s, or (b) a forward gap exceeding "
        f"max({SEGMENT_GAP_MULTIPLE}× the stream's own median interval, "
        f"{SEGMENT_GAP_MIN_SECONDS} s). The threshold is relative because the dataset spans "
        "~2 Hz to ~1000 Hz streams; one absolute value would over-segment slow streams and "
        "under-segment fast ones. Every segment records the exact reason it begins.\n\n"
        f"- Segments produced: **{len(result.segments)}** from {len(result.reads)} files.\n"
        f"- Files yielding more than one segment: **{len(multi_segment)}** "
        f"({len({Path(t.source_file).name for t in multi_segment})} distinct recordings; the "
        "dataset files the same recording under several family directories).\n"
    )
    if multi_segment:
        add("\n")
        add(
            _table(
                ["File", "Segments", "Clock resets", "Large gaps"],
                [
                    [
                        # The parent directory disambiguates the repeated copies.
                        f"`{Path(t.source_file).parent.name}/{Path(t.source_file).name}`",
                        str(t.segment_count),
                        str(t.clock_reset_count),
                        str(t.large_gap_count),
                    ]
                    for t in sorted(multi_segment, key=lambda x: (-x.segment_count, x.source_file))[
                        :15
                    ]
                ],
            )
        )
    add("\nFull listing: `segment_inventory.csv`.\n")

    # 9 -------------------------------------------------------------------
    add("\n## 9. Synchronization\n")
    if not result.sync:
        add(
            "_No paired sessions were available in this run, so no synchronization was "
            "attempted. Smartphone streams without a paired vehicle stream fall back to "
            "Tier-3 labels (see §10)._\n"
        )
    add(
        "Each S/V pair is aligned **individually**. There is no universal offset: Phase 1 "
        "found most pairs near-aligned and a minority about an hour apart. The estimator "
        "cross-correlates the two speed signals (smartphone GNSS speed against vehicle "
        "velocity) on a 0.1 s grid around the coarse clock difference, and reports the "
        "method and confidence rather than a bare number.\n\n"
    )
    add(
        _table(
            ["Status", "Pairs", "Meaning"],
            [
                [
                    f"`{SyncStatus.CONFIRMED_BY_SIGNAL}`",
                    str(sync_status.get(str(SyncStatus.CONFIRMED_BY_SIGNAL), 0)),
                    "speed correlation found a clear, well-separated peak",
                ],
                [
                    f"`{SyncStatus.CLOCK_ONLY}`",
                    str(sync_status.get(str(SyncStatus.CLOCK_ONLY), 0)),
                    "clocks overlap but the signal did not confirm the alignment",
                ],
                [
                    f"`{SyncStatus.UNRESOLVED}`",
                    str(sync_status.get(str(SyncStatus.UNRESOLVED), 0)),
                    "no trustworthy alignment; left unresolved rather than forced",
                ],
            ],
        )
    )
    confirmed = [s for s in result.sync if s.status == SyncStatus.CONFIRMED_BY_SIGNAL]
    offsets = [s.estimated_offset_s for s in result.sync if s.estimated_offset_s is not None]
    drifts = [
        s.drift_estimate_s
        for s in result.sync
        if s.drift_estimate_s is not None and np.isfinite(s.drift_estimate_s)
    ]
    add(
        f"\n- Confirmation threshold: correlation ≥ {MIN_CORRELATION} with a distinct peak, "
        f"and ≥ {MIN_OVERLAP_S:.0f} s of aligned overlap.\n"
        f"- Median correlation among confirmed pairs: "
        f"{_fmt(_median_correlation(confirmed))}.\n"
        f"- Estimated offsets span {_fmt(min(offsets) if offsets else None, 1, ' s')} to "
        f"{_fmt(max(offsets) if offsets else None, 1, ' s')}; median "
        f"{_fmt(statistics.median(offsets) if offsets else None, 2, ' s')}.\n"
        f"- Pairs with drift over 1 s across the session: "
        f"**{len([d for d in drifts if abs(d) > 1.0])}** of {len(drifts)}. Drift is reported "
        "per pair (in ppm) and never corrected here.\n\n"
        "Per-pair detail: `synchronization_results.csv`.\n"
    )

    # 10 ------------------------------------------------------------------
    add("\n## 10. Reference-state construction\n")
    add(
        "Targets are drawn from a strict hierarchy, and every labelled row records which "
        "tier produced it:\n\n"
    )
    add(
        _table(
            ["Tier", "Source", "Quality", "Segments"],
            [
                [
                    f"`{name}`",
                    {
                        "TIER_1_VEHICLE_SYNCED": "vehicle velocity, alignment confirmed by signal",
                        "TIER_2_VEHICLE_CLOCK": "vehicle velocity, clock-only alignment",
                        "TIER_3_SMARTPHONE_GNSS": "smartphone GNSS speed on fresh rows only",
                        "UNAVAILABLE": "no defensible target",
                    }.get(name, ""),
                    TIER_QUALITY.get(name, ""),
                    str(count),
                ]
                for name, count in sorted(label_sources.items())
            ],
        )
    )
    coverages = [label.coverage_fraction for label in result.labels]
    add(
        f"\n- Median label coverage per segment: "
        f"{_fmt(statistics.median(coverages) if coverages else None, 4)}.\n"
        f"- Vehicle velocity is interpolated onto smartphone sample times, but **only where a "
        f"reference sample lies within {MAX_INTERPOLATION_GAP_S} s**; further than that the row "
        "is left unlabelled rather than extrapolated.\n"
        "- Tier 3 exists only as a last resort and is flagged "
        "`REFERENCE_LOW_CONFIDENCE`, because the smartphone position updates at ~0.1 Hz.\n\n"
        "Per-segment detail: `reference_label_inventory.csv`.\n"
    )

    # 11 ------------------------------------------------------------------
    add("\n## 11. GNSS freshness\n")
    phone_intervals = [
        r.median_update_interval_s
        for r in result.freshness
        if r.stream == "smartphone" and r.median_update_interval_s
    ]
    vehicle_intervals = [
        r.median_update_interval_s
        for r in result.freshness
        if r.stream == "vehicle" and r.median_update_interval_s
    ]
    add(
        "Every row of every stream reports a valid fix, but that is not the same as a *fresh* "
        "position. Canonical records therefore carry `gnss_fix_available`, "
        "`gnss_position_fresh` and `gnss_stale_duration_s`.\n\n"
    )
    add(
        _table(
            ["Stream", "Median position-update interval", "Streams"],
            [
                [
                    "smartphone",
                    _fmt(statistics.median(phone_intervals) if phone_intervals else None, 3, " s"),
                    str(len(phone_intervals)),
                ],
                [
                    "vehicle",
                    _fmt(
                        statistics.median(vehicle_intervals) if vehicle_intervals else None,
                        3,
                        " s",
                    ),
                    str(len(vehicle_intervals)),
                ],
            ],
        )
    )
    stale_rows = sum(r.stale_rows for r in result.freshness)
    add(
        f"\nA row is flagged `GNSS_STALE` once its position has been held longer than "
        f"max({STALE_UPDATE_MULTIPLE}× that stream's own median update interval, "
        f"{STALE_MIN_SECONDS} s) — derived per stream because the smartphone updates ~9 s and "
        f"the vehicle ~0.1 s. **{stale_rows:,} row(s)** are flagged stale.\n\n"
        "**`GNSS_STALE` is staleness, not loss of signal.** There are still zero confirmed "
        "GNSS outages in IO-VNBD, and Phase 2 created none. Synthetic GNSS-denial episodes "
        "belong to a later phase.\n\n"
        "Per-stream detail: `gnss_freshness_report.csv`.\n"
    )

    # 12 ------------------------------------------------------------------
    add("\n## 12. Quality handling\n")
    add(
        "Problems become flags, not deletions. The closed vocabulary is stored in "
        "`canonical_schema.json`:\n\n"
    )
    add(
        _table(
            ["Flag", "Bit", "Meaning"],
            [
                [f"`{flag.name}`", str(int(flag.value)), (flag.__doc__ or "").strip()]
                for flag in QualityFlag
                if flag.name and flag.value
            ][:0]
            or [
                [f"`{flag.name}`", str(int(flag.value)), ""]
                for flag in QualityFlag
                if flag.name and flag.value
            ],
        )
    )
    add(
        f"\n- Processing errors: **{len(result.errors)}** ({len(failed)} failed). "
        "`processing_errors.csv` is always written, with zero rows when there are none — "
        "an absent artifact would be indistinguishable from an unrun stage.\n"
        "- No row was dropped for being suspicious. Missing numerics are NaN; availability is "
        "explicit.\n"
    )

    # 13 ------------------------------------------------------------------
    add("\n## 13. Duplicate-content split strategy\n")
    add(
        "Phase 1 found 235 byte-identical duplicate files. Phase 2 found **15 further "
        "groups whose files differ only in header labels while their data rows are "
        "byte-identical** — 314 distinct payloads behind 329 distinct file hashes. Splitting "
        "on the file hash alone would therefore still leak.\n\n"
        "Splits group on a **payload hash** (SHA-256 of everything after the header line), "
        "then take the transitive closure with shared `(dataset_family, session_id)`. That "
        "closure matters: the same session is filed under several family directories, and a "
        "shared payload chains those copies into one group.\n\n"
        "Whole groups are then packed **largest-first into whichever split is furthest below "
        "its target row count**. Hashing groups onto cumulative ratio boundaries was tried "
        "first and rejected: it balances *group counts*, and because group sizes span orders "
        "of magnitude it left the test split with under 1% of the rows. Determinism is kept "
        "by sorting on `(-rows, sha256(seed:group_key), key)`, so nothing depends on "
        f"wall-clock or dict iteration order.\n\nDefault ratios: {DEFAULT_RATIOS}.\n"
    )
    if result.split_summary:
        summary = result.split_summary
        add("\n")
        add(
            _table(
                ["Split", "Segments", "Rows", "Duration (h)"],
                [
                    [
                        name,
                        str(summary.counts.get(name, 0)),
                        f"{summary.rows.get(name, 0):,}",
                        f"{summary.duration_s.get(name, 0.0) / 3600:.1f}",
                    ]
                    for name in sorted(summary.counts)
                ],
            )
        )
        add(
            f"\n- Groups: **{summary.group_count}** covering {summary.segment_count} segments.\n"
            f"- Leakage violations: **{len(result.leakage_violations)}** "
            "(a payload or session appearing in more than one split).\n"
        )
    if result.content_audit is not None:
        audit = result.content_audit
        add(
            "\n**Content-level audit.** The payload hash sees only byte-identical data rows, "
            "so two copies of one recording written with different numeric formatting would "
            "look distinct to it. Every written segment is therefore fingerprinted a second "
            "time from its *parsed* sensor values (rounded to 1e-6) and the split re-checked "
            f"against that equivalence: **{audit.segments_fingerprinted}** segment(s), "
            f"**{audit.distinct_content_groups}** distinct content group(s), of which "
            f"**{audit.duplicate_content_groups}** hold more than one segment despite "
            f"differing payload hashes. Violations: **{len(audit.violations)}**.\n"
        )
    add(
        "\nSegments are assigned whole, so overlapping windows drawn from one trip can never "
        "straddle a split boundary. Rows and windows are **never** split randomly.\n"
    )

    # 14 ------------------------------------------------------------------
    add("\n## 14. ML-ready data contract\n")
    default = WindowConfig()
    add(
        "Canonical data is stored as **Parquet** (snappy), one file per segment under "
        "`data/processed/io_vnbd/<stream>/`. Parquet was chosen for columnar reads (a model "
        "needing six channels does not pay for sixty), preserved numeric dtypes, good "
        "compression on this volume, first-class Windows/pandas/pyarrow support, and chunked "
        "reading. Pickle was rejected outright for multi-million-row data.\n\n"
        "Sequence windows are **generated on demand**, not materialized, so a later "
        "experiment can change the geometry without regenerating a corpus. Defaults: "
        f"`duration_seconds={default.duration_seconds}`, "
        f"`stride_seconds={default.stride_seconds}`, "
        f"`min_coverage={default.min_coverage}` — a starting point, not a finding.\n\n"
        "**Causality is enforced:** for a target at time *t*, the window contains only "
        "samples with time ≤ *t*. A test asserts no future sample can enter a window.\n"
    )

    # 15 ------------------------------------------------------------------
    add("\n## 15. Statistics\n")
    rates = [t.measured_rate_hz for t in result.timing if t.measured_rate_hz]
    durations = [s.duration_s for s in result.segments if np.isfinite(s.duration_s)]
    add(
        f"- Canonical rows: **{total_rows:,}** ({result.row_counts}).\n"
        f"- Measured rate across streams: median "
        f"{_fmt(statistics.median(rates) if rates else None, 3, ' Hz')}, range "
        f"{_fmt(min(rates) if rates else None, 2)}–{_fmt(max(rates) if rates else None, 2)} Hz "
        "— heterogeneity preserved, not normalized away.\n"
        f"- Segment duration: median "
        f"{_fmt(statistics.median(durations) / 60 if durations else None, 1, ' min')}, "
        f"total {_fmt(sum(durations) / 3600 if durations else None, 1, ' h')}.\n"
    )
    labelled = [label for label in result.labels if label.mean_label_mps is not None]
    if labelled:
        means = [label.mean_label_mps for label in labelled if label.mean_label_mps]
        stationary = [
            label.stationary_fraction for label in labelled if label.stationary_fraction is not None
        ]
        add(
            f"- Reference velocity: mean across segments "
            f"{_fmt(statistics.median(means) if means else None, 2, ' m/s')}; median stationary "
            f"fraction (<0.5 m/s) "
            f"{_fmt(statistics.median(stationary) if stationary else None, 3)}.\n"
        )
    add(
        "\nThese are descriptive only. No training normalization was computed here — that "
        "must be derived from the training partition alone, in the phase that trains.\n"
    )

    # 16 ------------------------------------------------------------------
    add("\n## 16. Diagnostics\n")
    if plot_paths:
        add("Generated under `reports/io_vnbd/phase2_plots/` (Phase 1 figures untouched):\n\n")
        for plot in sorted(plot_paths):
            add(f"- `{plot.name}`\n")
    else:
        add("_No plots were generated._\n")

    # 17 ------------------------------------------------------------------
    add("\n## 17. Processing performance\n")
    add(
        f"- Wall time: **{result.elapsed_s:.1f} s** for {len(result.reads)} files "
        f"({total_rows:,} rows).\n"
        "- CSVs are read in chunks and canonicalized incrementally; memory is bounded by the "
        "chunk size plus one segment's frame, not by the dataset.\n"
        "- Each source file is read once for canonicalization. Sequence windows are computed "
        "lazily from Parquet rather than duplicated on disk.\n"
    )

    # 18 ------------------------------------------------------------------
    add("\n## 18. Limitations\n")
    add(
        "- **Synchronization is inferred, never documented.** No ground-truth alignment "
        "exists in IO-VNBD, so even a confirmed pair rests on a correlation argument.\n"
        "- **Gyroscope axis semantics are unverified.** Positional mapping is well evidenced; "
        "the yaw/pitch/roll labels are not, and no device→vehicle rotation is estimated here.\n"
        "- **The satellite field's `a / b` reading is an interpretation.** The raw string is "
        "preserved so it can be revisited.\n"
        "- **Timezone is unresolved.** `timestamp_utc` carries the smartphone's wall clock as "
        "written; whether it is UTC or local is not stated by the dataset.\n"
        "- **Sub-hour offsets and drift remain in the data.** Phase 2 measures them and "
        "leaves the streams untouched.\n"
        "- **Segment boundaries are a threshold choice.** The rule is documented and "
        "reproducible, but a different threshold would yield different trips.\n"
        "- **No GNSS-denial data exists.** Anything resembling an outage must be synthesized "
        "later and labelled synthetic.\n"
    )

    # 19 ------------------------------------------------------------------
    add("\n## 19. Phase 3/5 implications and data contract\n")
    add("### Available smartphone channels (canonical names)\n")
    add(
        "`accel_x/y/z`, `gyro_x/y/z`, `mag_x/y/z`, `gravity_x/y/z`, "
        "`orientation_yaw/pitch/roll`, `latitude`, `longitude`, `altitude_m`, "
        "`gnss_speed_mps`, `gnss_accuracy_m`, `gnss_heading_deg`, "
        "`gnss_satellites_raw` / `_in_use` / `_in_view`, `gnss_fix_available`, "
        "`gnss_position_fresh`, `gnss_stale_duration_s`.\n\n"
        "Magnetometer and orientation are **absent in the reduced 18-column files** — check "
        "`has_magnetometer` / `has_orientation` before using them.\n"
    )
    add("\n### Available reference targets\n")
    add(
        "`ref_velocity_mps` (with `label_source`, `label_quality`, `label_available`), plus "
        "the full vehicle channel set: `ref_speed_mps`, `ref_indicated_speed_mps`, "
        "`ref_yaw_rate_dps`, `ref_accel_long_mps2`, `ref_accel_lat_mps2`, "
        "`ref_wheel_speed_*`, `ref_steering_angle_deg`, `ref_engine_speed_rpm`, "
        "`ref_gear`, `ref_brake_*`, and others.\n"
    )
    add("\n### Reliable synchronization subset\n")
    add(
        f"Pairs with `status = {SyncStatus.CONFIRMED_BY_SIGNAL}` "
        f"(correlation ≥ {MIN_CORRELATION}, distinct peak, ≥ {MIN_OVERLAP_S:.0f} s overlap) "
        f"— **{len(confirmed)} pair(s)** in this run. These carry Tier-1 labels.\n"
    )
    add("\n### Known unusable / low-confidence records\n")
    add(
        "- Rows flagged `SYNC_UNRESOLVED` or `REFERENCE_LOW_CONFIDENCE`.\n"
        "- Tier-3 (smartphone-GNSS) labels.\n"
        "- Segments marked `is_short`.\n"
        "- Rows flagged `SCHEMA_REPAIR` (repaired, but from a defective source).\n"
    )
    add("\n### Known missing signals\n")
    add(
        "- No magnetometer/orientation in the 18-column files.\n"
        "- No documented GNSS outage, anywhere.\n"
        "- No country, road type, or scenario semantics.\n"
        "- No device mounting or calibration information.\n"
    )
    add("\n### Timestamp guarantees Phase 3 CAN assume\n")
    add(
        "- Every canonical row has `source_time_s` exactly as written, plus "
        "`analysis_time_s` on a continuous clock and `elapsed_s` measured from its "
        "segment start.\n"
        "- Within a segment, `elapsed_s` is non-decreasing.\n"
        "- A segment never spans a clock reset or a large gap.\n"
    )
    add("\n### What Phase 3 must NOT assume\n")
    add(
        "- **Not** 10 Hz smartphone sampling — measured rates vary; read `measured_rate_hz`.\n"
        "- **Not** perfect synchronization — check `status` and `offset_confidence` per pair.\n"
        "- **Not** a fresh GNSS fix on every row — check `gnss_position_fresh`.\n"
        "- **Not** that gyroscope yaw/pitch/roll labels denote vehicle axes.\n"
        "- **Not** that a file is one trip — use `segment_id`.\n"
        "- **Not** that file identity is content identity — group on `payload_hash`.\n"
        "- **Not** that any GNSS gap in this data is a real outage. There are none.\n"
    )

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("".join(lines), encoding="utf-8")
    return output
